version: '3.8'

services:
  valentine-xuraj:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valentine-xuraj
    ports:
      - "6000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
