version: '3.8'

services:
  valentine-samir:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valentine-samir
    ports:
      - "7000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
