version: '3.8'

services:
  valentine-roman:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valentine-roman
    ports:
      - "5000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
